### ISSUE TITLE
How to apply for a Māori Dictionary API Key?

### ISSUE THREAD

**Issue by jcop007** [dnadesign/silverstripe-audio-definition#2]
Hi

I can't seem to find any info on how to apply for an API key from https://maoridictionary.co.nz/ or even how to contact them.  Could you provide any info on this?

Thanks

**Comment by alex-dna** [comment]
Hi Jonathan,

thanks for your interest.
Best if you get in touch with our client for whom we developed this module: greg.synnott@wellingtonnz.com 
Greg should be able to tell you what is the process to get the key.

Thanks.
Alex

**Comment by alex-dna** [comment]
@jcop007 Did you have any luck getting the API key? IF yes, would you mind share the process you went through, I might put it in the README.

**Comment by jcop007** [comment]
@alex-dna Not yet, but I'm now in contact with the right person. I'll let you know.
